on:
    push:
        branches: main
    workflow_dispatch:
jobs:
    sync-template:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Sync template
              uses: ahmadnassri/action-template-repository-sync@v2
              with:
                  github-token: ${{ secrets.GH_TOKEN }}
                  dry-run: false
